FC 			= ifort
FCFLAGS 	= -O2

LIBS 		= -L/usr/local/lib
INCLUDES 	= -I/usr/local/include

LDFLAGS 	= /usr/local/lib/libfdf.a

SOURCE 		= iochamp.f90 
MODULES		= m_periodic_table.F90 	m_keywords.F90
OBJECTS		= m_periodic_table.o m_keywords.o
PROJECT 	= iochamp.o

