# This is a basic workflow to help you get started with Actions

name: Continuous Integration on Panhala

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the minimal branch
  push:
    branches: [ minimal ]
  pull_request:
    branches: [ minimal ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Compile the code
        run: |
          echo Compiling the code in the directory
          echo Running using a self-hosted runner
#          cd fparser/modified-libfdf
#          ./configure FC=ifort CC=icc --prefix=$PWD
#          make clean
#          make 
#          make install
#          make check
